/**
 * Write the development overlays that mount this checkout.
 *
 * A patch row resolves module paths from the profile directory, so the rows
 * need this machine's absolute paths; these files are generated rather than
 * committed for that reason.
 *
 *   .dev/cordis.yml         the source rows: what a developer iterates on
 *   .dev/built.yml          the built rows: the artifact shape a deployment loads
 *   .dev/install-probe.yml  the probe row: what an installed profile produced
 *
 * The dialect is its own row, before the plugin, because the plugin ships no
 * database type and writes its tool descriptions from a dialect's own facts.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
// A `file://` URL, not a bare path: the Loader hands the row name to
// `import()`, where `S:/...` would read as a URL scheme.
const asRow = relative => pathToFileURL(resolve(root, relative)).href
const generated = name => resolve(root, '.dev', name)

/** The composition values every plugin row starts on. */
const CONFIG = [
  '      config:',
  '        dialect: mysql',
  '        host: 127.0.0.1',
  "        database: ''",
  '        maxRows: 200',
]

/** One overlay's file name and its lines. */
const OVERLAYS = {
  'cordis.yml': [
    '# Generated by scripts/dev-overlay.mjs — mounts this checkout’s sources.',
    '# Usage, from the harness checkout: pnpm dsh --profile web --patch <this file>',
    '- insert:',
    '    - id: dialect-mysql',
    `      name: '${asRow('dialects/mysql/src/index.ts')}'`,
    '    - id: ds-db',
    `      name: '${asRow('src/index.ts')}'`,
    ...CONFIG,
  ],
  'built.yml': [
    '# Generated by scripts/dev-overlay.mjs — mounts the BUILT artifacts, the',
    '# shape a deployment loads. Build first: pnpm run build',
    '# Usage, from the harness checkout: pnpm dsh --profile web --patch <this file>',
    '- insert:',
    '    - id: dialect-mysql',
    `      name: '${asRow('dialects/mysql/lib/index.js')}'`,
    '    - id: ds-db',
    `      name: '${asRow('lib/index.js')}'`,
    ...CONFIG,
  ],
  'install-probe.yml': [
    '# Generated by scripts/dev-overlay.mjs — mounts the probe that reports what an',
    '# installed profile produced (dialects and tools), then exits by itself.',
    '# Usage: dsh --profile <name> --patch <this file>',
    '- insert:',
    '    - id: install-probe',
    `      name: '${asRow('scripts/install-probe.mjs')}'`,
  ],
}

mkdirSync(resolve(root, '.dev'), { recursive: true })
for (const [name, lines] of Object.entries(OVERLAYS)) {
  writeFileSync(generated(name), `${lines.join('\n')}\n`)
  console.log(`wrote .dev/${name}`)
}
console.log(`source rows: ${asRow('src/index.ts')}`)
console.log(`built rows:  ${asRow('lib/index.js')}`)
