/**
 * Write the development overlay that mounts this checkout's plugin source.
 *
 * A patch row resolves module paths from the profile directory, so the row
 * needs this machine's absolute path; the file is generated rather than
 * committed for that reason.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
// A `file://` URL, not a bare path: the Loader hands the row name to
// `import()`, where `S:/...` would read as a URL scheme.
const entry = pathToFileURL(resolve(root, 'src/index.ts')).href
const overlay = resolve(root, '.dev/cordis.yml')

mkdirSync(dirname(overlay), { recursive: true })
writeFileSync(overlay, [
  '# Generated by scripts/dev-overlay.mjs — mounts this checkout\'s plugin source.',
  '# Usage, from the harness checkout: dsh web --patch <this file>',
  '- insert:',
  '    - id: ds-db',
  `      name: '${entry}'`,
  '      config:',
  '        host: 127.0.0.1',
  "        database: ''",
  '        maxRows: 200',
  '',
].join('\n'))

console.log(`wrote ${overlay}`)
console.log(`row entry: ${entry}`)
