/**
 * Write the development overlay that mounts this checkout's plugin and its
 * bundled dialect.
 *
 * A patch row resolves module paths from the profile directory, so the rows
 * need this machine's absolute paths; the file is generated rather than
 * committed for that reason.
 *
 * The dialect is its own row, before the plugin, because the plugin ships no
 * database type and writes its tool descriptions from a dialect's own facts.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
// A `file://` URL, not a bare path: the Loader hands the row name to
// `import()`, where `S:/...` would read as a URL scheme.
const asRow = relative => pathToFileURL(resolve(root, relative)).href
const overlay = resolve(root, '.dev/cordis.yml')

mkdirSync(dirname(overlay), { recursive: true })
writeFileSync(overlay, [
  '# Generated by scripts/dev-overlay.mjs — mounts this checkout’s plugin and its dialect.',
  '# Usage, from the harness checkout: dsh web --patch <this file>',
  '- insert:',
  '    - id: dialect-mysql',
  `      name: '${asRow('dialects/mysql/src/index.ts')}'`,
  '    - id: ds-db',
  `      name: '${asRow('src/index.ts')}'`,
  '      config:',
  '        dialect: mysql',
  '        host: 127.0.0.1',
  "        database: ''",
  '        maxRows: 200',
  '',
].join('\n'))

console.log(`wrote ${overlay}`)
console.log(`dialect row: ${asRow('dialects/mysql/src/index.ts')}`)
console.log(`plugin row:  ${asRow('src/index.ts')}`)
